### ISSUE TITLE
Add ability to download shp

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapfilter#12]
We should have a way to download the data as a SHP file, to be used in other GIS software.

**Comment by jlev** [comment]
Added CSV download feature to branch spacedogXYZ/mapfilter#feature/file-download:
https://github.com/spacedogXYZ/mapfilter/compare/master...spacedogXYZ:feature/file-download?expand=1

Can send a pull request after feature/generic-template is merged. Or you can cherry pick from branch directly.
